---
- hosts: workstation
  gather_facts: False
  become: True
  vars_files:
    - vars/tower.yaml

  tasks:
    - name: Delete VMs
      virt: 
        name: "{{ item.key }}"
        command: destroy
      loop: "{{ vms | dict2items }}"
      
    - name: undefine VMs
      virt: 
        name: "{{ item.key }}"
        command: undefine
      loop: "{{ vms | dict2items }}"
      
    - name: remove VM Disks
      file: 
        path: "{{ vmdir }}{{ item.key }}.qcow2" 
        state: absent
      loop: "{{ vms | dict2items }}"

    - name: remove Additional Disks
      file: 
        path: "{{ diskdir }}{{ item.key }}_addisk.qcow2" 
        state: absent
      when: item.value.addisk is defined
      loop: "{{ vms | dict2items }}"

    - name: remove Network
      virt_net:
        name: "{{ vmnet.netname }}"
        state: absent